pycs/controllers/assignment.py
from datetime import datetime

from flask import flash
from sqlalchemy.exc import IntegrityError

from pycs.extensions import db
from pycs.models import Assignment, User, UserAssignment, Weighting


def create_assignment(new_ass):
    """Create a new assignment"""
    db.session.add(new_ass)
    db.session.commit()


def get_all_assignments():
    """Get all assignments"""
    return (
        db.session.execute(db.select(Assignment).order_by(db.desc(Assignment.id)))
        .scalars()
        .all()
    )


def get_assignment_by_id(a_id: int):
    """Get an assignment by it's id"""
    return db.session.execute(
        db.select(Assignment).where(Assignment.id == a_id)
    ).scalar_one_or_none()


def get_class_assignments_of_user(class_id: int, user_id: int):
    """Get all assignments, and all the scores of all the assignments.
    If an assignment has not been submitted, the UserAssignment is None"""
    assignments_scores = db.session.execute(
        db.select(Assignment, UserAssignment)
        .outerjoin(
            UserAssignment,
            (UserAssignment.assignment_id == Assignment.id)
            & (UserAssignment.user_id == user_id),
        )
        .where(Assignment.class_id == class_id)
        .order_by(db.desc(Assignment.id))
    )
    return assignments_scores


def score_ass(user, assignment, score, comments):
    """Add a new User_Assignment association, thus grading the student's assignment"""
    user_assignment = UserAssignment(user_id=user.id, score=score, comments=comments)
    db.session.commit()
    assignment.user_associations.append(user_assignment)
    user.assignment_associations.append(user_assignment)
    db.session.commit()


def update_ass_score(user_assignment, score, comments):
    """Update the score and comments on a particular assignment"""
    user_assignment.score = score
    user_assignment.comments = comments
    db.session.commit()


def upload_assignment_grades(a_id, grades) -> int:
    """Upload grades from a csv file

    Returns:
        The number of grades successfully input
    """

    count = 0
    ass = get_assignment_by_id(a_id)
    if ass is None:
        return count

    for grade_item in grades:
        if "Score" not in grade_item or "Email" not in grade_item:
            flash("CSV must contain Email and Score headings", "error")
            return 0
        # D2L has student number under Email column
        student_number = grade_item["Email"]
        user = db.session.execute(
            db.select(User).where(User.student_number == student_number)
        ).scalar_one_or_none()
        if user is None:
            flash(f"Could not upload marks for {grade_item['First Name']}", "error")
            continue
        # Check to see if a score exists
        ua = db.session.execute(
            db.select(UserAssignment).where(
                UserAssignment.user_id == user.id, UserAssignment.assignment_id == a_id
            )
        ).scalar_one_or_none()
        score = float(grade_item["Score"]) if grade_item["Score"].strip() != "" else 0
        if ua is None:
            score_ass(user, ass, score, "Uploaded from D2L")
        else:
            update_ass_score(ua, score, "Uploaded from D2L")
        count += 1
    return count


def assignments_scores_to_dict(assignments_scores):
    assignments = {}
    for a, ua in assignments_scores:
        if a.unit_name not in assignments:
            assignments[a.unit_name] = []

        if ua is None:
            if a.due_date < datetime.today():
                score = 0
            else:
                score = None
        else:
            score = ua.score

        # Don't send invisible assignments
        if a.visible:
            assignments[a.unit_name].append(
                {
                    "id": a.id,
                    "name": a.name,
                    "due_date": a.due_date,
                    "score": score,
                    "total_points": a.total_points,
                    "total": a.total_points,
                    "class_id": a.class_id,
                }
            )

    return assignments


def calc_overall_avg(assignments_scores) -> float:
    """Calculate the student's average.
    Don't include missing assignments if we are not past the due date
    """
    # Get weightings from database
    weightings = db.session.execute(db.select(Weighting)).scalars()
    marks = {w.weight: [] for w in weightings}

    for a, ua in assignments_scores:
        if ua:
            marks[a.weighting.weight].append(ua.score / a.total_points)
        elif a.due_date < datetime.today():
            marks[a.weighting.weight].append(0)

    def _safe_len(lst: list) -> int:
        s = len(lst)
        return 1 if s == 0 else s

    avg = round(sum((sum(marks[w]) / _safe_len(marks[w]))*w for w in marks), 2)


    return avg

pycs/views/auth.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from sqlalchemy.exc import IntegrityError

from pycs.controllers import user as user_controller
from pycs.exc import JoinCodeInvalidException
from pycs.forms import ChangePassForm, LoginForm, RegisterForm

from . import login_required

bp = Blueprint("auth", __name__)


@bp.route("/register", methods=["GET", "POST"])
def register():
    """Handles user registration."""
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            new_user = user_controller.create_student(
                student_number=form.student_number.data,
                first_name=form.first_name.data,
                password=form.password.data,
                join_code=form.join_code.data,
            )
        except IntegrityError:
            form.student_number.errors.append(
                f"Student {form.student_number.data} is already registered."
            )
        except JoinCodeInvalidException as e:
            form.join_code.errors.append(e)
        else:
            login_user(new_user)
            flash(
                f"Thanks for registering, {new_user.first_name}!",
                "info",
            )
            return redirect(url_for("main.index"))

    return render_template("auth/register.html", form=form)


@bp.route("/login", methods=["GET", "POST"])
def login():
    """Handles User login. Uses sessions through Flask-Login"""
    form = LoginForm()
    if form.validate_on_submit():
        remember = bool(form.data.get("remember"))

        user = user_controller.get_user_by_student_number(form.student_number.data)

        if user is None or not user_controller.verify_password(
            user.password_hash, form.password.data
        ):
            form.student_number.errors.append("Invalid Credentials.")
        else:
            login_user(user, remember)
            return redirect(url_for("main.index"))

    return render_template("auth/login.html", form=form)


@bp.get("/logout")
def logout():
    """Log the user out (Again, thanks Flask-Login)"""
    logout_user()
    return redirect(url_for("main.index"))


@bp.route("/changepass", methods=["GET", "POST"])
@login_required
def change_pass():
    """Handles the changing of a user's password."""
    form = ChangePassForm()
    if form.validate_on_submit():
        # Verify current password
        err_msg = user_controller.change_user_password(
            current_user, form.current_pass.data, form.new_pass.data
        )
        if err_msg is None:
            return redirect(url_for("main.index"))
        else:
            form.new_pass.errors.append(err_msg)

    return render_template("auth/changepass.html", form=form)

pycs/views/teacher.py
import csv
from datetime import datetime
import io
import os
from pathlib import Path

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    send_file,
    url_for,
)
import markdown
from werkzeug.utils import secure_filename

from pycs.controllers import user as user_controller
from pycs.controllers import assignment as ass_controller
from pycs.controllers import classroom as class_controller
from pycs.controllers import commit_change
from pycs.forms import AssignmentForm, ClassroomForm, UploadMarksForm
from pycs.models.assignment import Assignment
from pycs.models.classroom import Classroom

from . import teacher_login_required

bp = Blueprint("teacher", __name__)


@bp.get("/")
@teacher_login_required
def index():
    return render_template("teacher/home.html")


###############################################################################
####################           STUDENTS DASHBORD           ####################
###############################################################################


@bp.get("/students")
@teacher_login_required
def view_students():
    students = user_controller.get_all_students()
    return render_template("teacher/view_students.html", students=students)


@bp.get("/students/<int:student_number>/course/<int:class_id>")
@teacher_login_required
def view_student(student_number: int, class_id: int):
    user = user_controller.get_user_by_student_number(student_number)

    assignments_scores = ass_controller.get_class_assignments_of_user(class_id, user.id)

    # Needed so that the generator doesn't run out the second time I use it
    assignments_scores = list(assignments_scores)
    assignments = ass_controller.assignments_scores_to_dict(assignments_scores)
    student_avg = ass_controller.calc_overall_avg(assignments_scores)

    return render_template(
        "teacher/view_student.html",
        assignments=assignments,
        student_avg=student_avg,
        user=user,
        class_id=class_id,
        today=datetime.today(),
    )


@bp.get("/students/<int:student_number>/course/<int:class_id>/assignment/<int:a_id>")
@teacher_login_required
def view_student_assignment(student_number: int, class_id: int, a_id: int):
    user = user_controller.get_user_by_student_number(student_number)
    user_assignment = next(
        (ua for ua in user.assignment_associations if ua.assignment_id == a_id),
        None,
    )

    assignment = (
        ass_controller.get_assignment_by_id(a_id)
        if user_assignment is None
        else user_assignment.assignment
    )

    instructions = markdown.markdown(
        assignment.instructions, extensions=["fenced_code"]
    )
    return render_template(
        "teacher/view_student_assignment.html",
        assignment=assignment,
        instructions=instructions,
        data=user_assignment,
        user=user,
        form=None,
    )


###############################################################################
####################      ASSIGNMENTS DASHBORD             ####################
###############################################################################


@bp.get("/assignments")
@teacher_login_required
def view_assignments():
    assignments = ass_controller.get_all_assignments()
    return render_template("teacher/view_assignments.html", assignments=assignments)


@bp.route("/assignments/new", methods=["GET", "POST"])
@bp.route("/assignments/<int:a_id>", methods=["GET", "POST"])
@teacher_login_required
def view_edit_assignment(a_id: int | None = None):
    if a_id is not None:
        assignment = ass_controller.get_assignment_by_id(a_id)
    else:
        assignment = Assignment()

    form = AssignmentForm(obj=assignment)

    if form.validate_on_submit():
        # Commit changes to database
        form.populate_obj(assignment)
        if a_id is not None:
            commit_change()
        else:
            ass_controller.create_assignment(assignment)

        # Handle upload of pytest/junit files (optional)
        if form.unit_test_upload.data is not None:
            uploaded_file = form.unit_test_upload.data
            filename = secure_filename(uploaded_file.filename)
            _, ext = os.path.splitext(filename)
            upload_error = None
            if ext == ".py":
                pytest_upload_dir = os.path.join(
                    current_app.config["UPLOAD_FOLDER"], "tests"
                )
                if not os.path.exists(pytest_upload_dir):
                    os.makedirs(pytest_upload_dir)

                upload_path = os.path.join(pytest_upload_dir, filename)

                try:
                    uploaded_file.save(pytest_upload_dir)
                except OSError:
                    upload_error = f"Could not upload file {filename}: OSError"
            elif ext == ".java":
                junit_upload_dir = os.path.join(
                    current_app.config["UPLOAD_FOLDER"], "tests-java"
                )
                if not os.path.exists(junit_upload_dir):
                    os.makedirs(junit_upload_dir)

                upload_path = os.path.join(junit_upload_dir, filename)

                try:
                    uploaded_file.save(upload_path)
                except OSError:
                    upload_error = f"Could not upload file {filename}: OSError"
            else:
                upload_error = f"Could not upload file, not .py or .java"

            if upload_error is not None:
                flash(upload_error)
        return redirect(url_for(".view_assignments"))

    return render_template("teacher/assignment_form.html", form=form)


###############################################################################
####################        CLASSES DASHBORD               ####################
###############################################################################


@bp.get("/classes")
@teacher_login_required
def view_classes():
    classrooms = class_controller.get_all_classes()
    current_app.logger.info("Classrooms :D" + str(len(classrooms)))
    return render_template("teacher/view_classes.html", classrooms=classrooms)


@bp.route("/classes/new", methods=["GET", "POST"])
@bp.route("/classes/<int:class_id>", methods=["GET", "POST"])
@teacher_login_required
def view_edit_classes(class_id: int | None = None):
    if class_id is not None:
        classroom = class_controller.get_classroom_by_id(class_id)
    else:
        classroom = Classroom()

    form = ClassroomForm(obj=classroom)

    if form.validate_on_submit():
        form.populate_obj(classroom)
        if class_id is not None:
            commit_change()
        else:
            class_controller.create_class(classroom)

        return redirect(url_for(".view_classes"))

    return render_template("teacher/class_form.html", form=form)


###############################################################################
####################        Mark Import / Export           ####################
###############################################################################


@bp.get("/import")
@teacher_login_required
def import_marks():
    assignments = ass_controller.get_all_assignments()
    return render_template(
        "teacher/view_assignments_for_import.html", assignments=assignments
    )


@bp.route("/import/<int:a_id>", methods=["GET", "POST"])
def assignment_import(a_id):
    form = UploadMarksForm()
    if form.validate_on_submit():
        grades = csv.DictReader(io.StringIO(form.marks.data.read().decode("utf-8")))
        count = ass_controller.upload_assignment_grades(a_id, grades)
        if count != 0:
            flash(f"{count} grades uploaded", "info")
        else:
            flash("There was an issue uploading grades", "error")
        return redirect(url_for(".import_marks"))

    return render_template("teacher/import_assignment.html", form=form)


def _export_marks(class_id: int) -> (str, str):
    # Create a file
    classroom = class_controller.get_classroom_by_id(class_id)
    # Header row
    header = ",".join(
        ["Name", "Student Number", "Average"]
        + [
            a.name
            for a in sorted(classroom.assignments, key=lambda x: x.id, reverse=True)
        ]
    )
    body = ""

    for user in classroom.users:
        assignment_scores = ass_controller.get_class_assignments_of_user(
            class_id, user.id
        ).fetchall()
        avg = ass_controller.calc_overall_avg(assignment_scores)
        body_line = ",".join(
            [user.first_name, user.student_number, str(avg)]
            + [str(ua.score) if ua else "0" for _, ua in assignment_scores]
        )
        # body_line = ",".join([user.first_name] + [str(ua.score) for ua in sorted(user.assignment_associations, key=lambda x: x.assignment_id)])
        body += body_line + "\n"

    file_name = Path(f"marks_{classroom.course_code}_{datetime.today()}.csv")
    file_directory = os.path.join(current_app.config["EXPORTED_FILES"])
    with open(file_directory / file_name, "w") as f_out:
        f_out.write(f"{header}\n{body}")

    return file_directory, file_name


@bp.get("/export3u")
@teacher_login_required
def export_3u_marks():
    file_directory, file_name = _export_marks(class_id=1)
    data = io.BytesIO()
    with open(file_directory / file_name, mode="rb") as f_out:
        data.write(f_out.read())
    data.seek(0)
    os.remove(file_directory / file_name)
    return send_file(
        data, mimetype="text/csv", download_name=str(file_name), as_attachment=True
    )


@bp.get("/export4u")
@teacher_login_required
def export_4u_marks():
    file_directory, file_name = _export_marks(class_id=2)
    data = io.BytesIO()
    with open(file_directory / file_name, mode="rb") as f_out:
        data.write(f_out.read())
    data.seek(0)
    os.remove(file_directory / file_name)
    return send_file(
        data, mimetype="text/csv", download_name=str(file_name), as_attachment=True
    )

pycs/templates/401.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Unauthorized</title>


  <style>
    html {
      background-color: rgb(36 41 51);
      color: rgb(236 239 244);
      font-size: 20px;
      padding: 2rem;
    }

    h1 {
      font-size: 2rem;
      color: rgb(191 97 106);
      text-align: center;
    }

    img {
      position: absolute;
      opacity: 0.3;
      top: 2rem;
      left: 50%;
      right: 50%;
      transform: translateX(-50%);
      z-index: -999;
    }

    .container {
      position: relative;
      margin-bottom: 5rem;
    }

    .small {
      font-size: 0.8rem;
    }
  </style>
</head>
<body>
  <div class="container">
    <img src="{{ url_for('static', filename='py.svg') }}" alt="Py Logo" width="250">
    <h1>401</h1>
    <p>Whoa there, hacker! Looks like you're trying to sneak into my Python-powered fortress. Unless you speak fluent Parseltongue, you won't find your way in. Better go back to the muggle realm and brush up on your Python &lt;3</p>
  </div>
  <p class="text-sm">Actual server response for those interested:</p>
  <p class="text-sm">{{ error }}</p>
</body>
</html>

pycs/templates/_button.html
{% macro button_link(url, text) %}
    <a class="p-2 rounded-md border border-nord-10 dark:border-nord-8 transition-colors hover:bg-nord-10 dark:hover:bg-nord-8 active:bg-nord-7 dark:active:bg-nord-9 focus:bg-nord-10 dark:focus:bg-nord-8" href="{{ url }}">{{ text }}</a>
{% endmacro %}

pycs/templates/_flash.html
{% macro display_flashes(field) %}
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<ul>
    {% for category, message in messages %}
    {% if category == "error" %}
    <li class="bg-nord-11 p-4 rounded-md mb-4">{{ message }}</li>
    {% else %}
    <li class="bg-nord-14 p-4 rounded-md mb-4">{{ message }}</li>
    {% endif %}
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endmacro %}

pycs/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="mb-4">
    {{ field.label(class="block mb-2") }}
    {{ field(class="w-full p-1 rounded-md", **kwargs)|safe }}
</div>
{% endmacro %}

{% macro render_submit(submit) %}
{{ submit(class="px-4 py-2 rounded-md border border-nord-10 dark:border-nord-8 transition-colors hover:bg-nord-10
dark:hover:bg-nord-8 active:bg-nord-7 dark:active:bg-nord-9 focus:bg-nord-10 dark:focus:bg-nord-8") }}
{% endmacro %}

{% macro render_submit_manual(button_text) %}
<input type="submit"
    class="px-4 py-2 rounded-md border border-nord-10 dark:border-nord-8 transition-colors hover:bg-nord-10 dark:hover:bg-nord-8 active:bg-nord-7 dark:active:bg-nord-9 focus:bg-nord-10 dark:focus:bg-nord-8"
    value="{{ button_text }}" />
{% endmacro %}

{% macro render_checkbox(checkbox) %}
<div class="mb-4">
    {{ checkbox.label(class="mb-2") }}
    {{ checkbox(class="ml-2") }}
</div>
{% endmacro %}

{% macro render_file_input(file_input) %}
<div class="mb-4">
    {{ file_input.label(class="block mb-2") }}
    {{ file_input(class="p-2 hover:cursor-pointer file:py-2 file:border file:border-nord-10 dark:file:border-nord-8
    file:rounded-md file:bg-nord-4 dark:file:bg-nord-10 file:transition-colors hover:file:bg-nord-10
    dark:hover:file:bg-nord-8") }}
</div>
{% endmacro %}

{% macro render_errors(errors) %}
<!-- Field errors -->
{% if errors %}
<ul>
    {% for _, ferrors in errors|dictsort if ferrors %}
    {% for error in ferrors %}
    <li class="bg-nord-11 p-4 rounded-md mb-4">{{ error }}</li>
    {% endfor %}
    {% endfor %}
</ul>
{% endif %}
{% endmacro %}

pycs/templates/_lists.html
{% macro render_list_item(title, title_url, sub_title=None, score=None, total_points=None) %}
<div class="flex justify-between items-center">
    <div>
        <div class="mb-2">
          <a href="{{ title_url }}" class="text-nord-10 hover:text-nord-8 dark:text-nord-8 dark:hover:text-nord-10 transition-colors">{{ title }}</a>
        </div>
        {% if sub_title %}
        <div class="text-sm opacity-70">{{ sub_title }}</div>
        {% endif %}
    </div>
    {% if score is not none%}
    <div>
      <span class="text-nord-14">{{ score }}</span>
      {% if total_points is not none %}
      <span>/ {{ total_points }}</span>
      {% endif %}
    </div>
    {% endif %}
</div>
{% endmacro %}


{% macro render_list_sep() %}
<hr class="border-nord-0 dark:border-nord-6 -mx-4">
{% endmacro %}

pycs/templates/app.html
{% extends 'base.html' %}

{% block title %}pycs/{% endblock %}

{% block content %}
<div class="container">
    <h2 class="current-avg">{{ avg }}%</h2>
    {% for unit, assignments in assignments_by_unit.items() %}
    <h1 class="unit-name">{{ unit }}</h1>
    <div class="container--surface ass-list">
        {% for a in assignments %}
        <div class="ass-list__ass">
            <div class="">
                <div class="ass__name">
                    <a class="ass__name__link {{ 'ass__name__link--overdue' if a.due_date < today }}" href="{{ url_for('.assignment', class_id=a.class_id, a_id=a.id) }}">{{ a.name }}</a>
                </div>
                <div class="ass__due">Due: {{ a.due_date.strftime("%a %b %d, %Y @ %H:%M") }}</div>
            </div>
            <div>
                {% if a.score is not none %}
                <span class="ass__score">{{ a.score }}</span>
                {% endif %}
                <span> / {{ a.total }}</span>
            </div>
        </div>
        {% if not loop.last %}
        <hr class="surface-divider">
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

pycs/templates/assignment.html
{% extends 'base.html' %}

{% block title %}pycs/assignment{% endblock %}

{% block content%}
<div class="container">
  <h1 class="assignment-title">{{ assignment.name }}</h1>
  <div class="container--surface">
    <!-- Field errors -->
    {% if form.errors %}
    <ul class="form-errors">
        {% for _, ferrors in form.errors|dictsort if ferrors %}
            {% for error in ferrors %}
                <li class="form-errors__error">{{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
    {% endif %}
    
    <form action="" method="post" enctype="multipart/form-data">
      {{ form.csrf_token }}
      <div class="form__input">
        {{ form.code(class="form__input__file") }}
      </div>
      <input class="form__input__submit" type="submit" value={{ "Upload" if not data else "ReUpload" }}>
    </form>
  </div>
</div>

<div class="container assignment-info">
  {% if data %}
  <h2 class="assignment-info__title">Grade: {{ data.score }} / {{ assignment.total_points }}</h2>
  {% else %}
  <h2 class="assignment-info__title">Not submitted yet!</h2>
  {% endif %}
  <p class="assignment-info__due">Due: {{ assignment.due_date.strftime("%a %b %d, %Y @ %H:%M") }}</p>
</div>

<div class="container assignment-comments">
  {% if data %}
  <pre class="assignment-comment">{{ data.comments }}</pre>
  {% endif %}
</div>
{% endblock %}

pycs/templates/base.html
{% from '_button.html' import button_link %}
{% from '_lists.html' import render_list_sep %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="color-scheme" content="dark light">
  <title>~/{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <!-- Syntax Highlighting -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/a11y-light.css" media="screen and (prefers-color-scheme: light)">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/a11y-dark.css" media="screen and (prefers-color-scheme: dark)">
  <link rel="stylesheet" href="https://unpkg.com/highlightjs-copy/dist/highlightjs-copy.min.css"/>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
  <script src="https://unpkg.com/highlightjs-copy/dist/highlightjs-copy.min.js"></script>
  <script>
    hljs.addPlugin(new CopyButtonPlugin());
    hljs.highlightAll();
  </script>
</head>
<body class="bg-nord-6 text-nord-0 dark:bg-nord-0 dark:text-nord-6 mb-8">
  <nav class="flex justify-between items-center p-4 bg-nord-4 dark:bg-nord-1 relative">
    <a class="text-2xl" href="{{ url_for('main.index') }}">PYCS</a>
    {% if current_user.is_authenticated %}
        <p>Hey {{ current_user.first_name }}!{% block studname %}{% endblock %}</p>
        <div class="flex items-center justify-center gap-4">
          {% if current_user.is_admin %}
              <a href="{{ url_for('teacher.index') }}" class="text-nord-10 hover:text-nord-8 dark:text-nord-8 dark:hover:text-nord-10 transition-colors">Admin</a>
          {% endif %}
          <a href="{{ url_for('auth.change_pass') }}" class="text-nord-10 hover:text-nord-8 dark:text-nord-8 dark:hover:text-nord-10 transition-colors">Change Password</a>
          <a href="{{ url_for('auth.logout') }}" class="text-nord-10 hover:text-nord-8 dark:text-nord-8 dark:hover:text-nord-10 transition-colors">Logout</a>
        </div>
    {% else %}
        <div class="flex items-center justify-center gap-4">
          {{ button_link(url_for('auth.register'), 'Register')}}
          {{ button_link(url_for('auth.login'), 'Login')}}
        </div>
    {% endif %}
  </nav> 

  <div class="container mx-auto p-4">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

pycs/templates/changepass.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block title %}register{% endblock %}

{% block content %}
<div class="container container--surface">
    <!-- Field errors -->
    {% if form.errors %}
        <ul class="form-errors">
            {% for _, ferrors in form.errors|dictsort if ferrors %}
                {% for error in ferrors %}
                    <li class="form-errors__error">{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <form class="form" method="post">
        {{ form.csrf_token }}
        {{ render_field(form.current_pass) }}
        {{ render_field(form.new_pass) }}
        {{ render_field(form.confirm_new_pass) }}
        {{ form.submit(class="form__input__submit")}}
    </form>
</div>

{% endblock %}

pycs/templates/landing.html
{% extends 'base.html' %}

{% block content %}
  <p class="text-lg">This is a tool created by Mr. Habib for checking the code of his ICS3U students. I call this tool Pycs.</p>
  <p class="text-lg">To use this tool, please register with your student number!</p>
{% endblock %}

pycs/templates/login.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block title %}login{% endblock %}

{% block content %}
<div class="container container--surface">
    <!-- Field errors -->
    {% if form.errors %}
        <ul class="form-errors">
            {% for _, ferrors in form.errors|dictsort if ferrors %}
                {% for error in ferrors %}
                    <li class="form-errors__error">{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <form class="form" method="post">
        {{ form.csrf_token }}
        {{ render_field(form.student_number) }}
        {{ render_field(form.password) }}
        <div class="form__input">
            {{ form.remember.label(class="form__input__label") }}
            {{ form.remember(class="form__input__box") }}
        </div>
        {{ form.submit(class="form__input__submit") }}
    </form>
</div>
{% endblock %}